var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/bodega/contadores/route.js")
R.c("server/chunks/[root-of-the-server]__0u-8xof._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_bodega_contadores_route_actions_01_dw4g.js")
R.m(100384)
module.exports=R.m(100384).exports
