var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/bodega/buscar/route.js")
R.c("server/chunks/[root-of-the-server]__13mc01n._.js")
R.c("server/chunks/[root-of-the-server]__0.p.4.i._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_09pj6ln._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/0t6k_@aws-sdk_core_dist-es_submodules_protocols_xml_XmlShapeDeserializer_011at9i.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__13kvue0._.js")
R.c("server/chunks/[root-of-the-server]__0l906zu._.js")
R.c("server/chunks/_next-internal_server_app_api_bodega_buscar_route_actions_12em.gl.js")
R.m(351778)
module.exports=R.m(351778).exports
