var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/cartera/recibo/[pagoId]/route.js")
R.c("server/chunks/[root-of-the-server]__085vgk_._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_cartera_recibo_[pagoId]_route_actions_0-b-tvy.js")
R.m(61947)
module.exports=R.m(61947).exports
