var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/rutas-fijas/meta-cliente/route.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0j0r4qo._.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0ofgmt.._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_rutas-fijas_meta-cliente_route_actions_0109sol.js")
R.m(970929)
module.exports=R.m(970929).exports
