var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/invalidate-cache/route.js")
R.c("server/chunks/[root-of-the-server]__0uox1.r._.js")
R.c("server/chunks/[root-of-the-server]__0ofgmt.._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_invalidate-cache_route_actions_04uz1n3.js")
R.m(565847)
module.exports=R.m(565847).exports
