var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/impulsar/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hezeez._.js")
R.c("server/chunks/ssr/node_modules_05l396c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_10wn8-b.js")
R.c("server/chunks/ssr/[root-of-the-server]__0khh7ip._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sc-y4u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(app)_layout_tsx_0i-3xbc._.js")
R.c("server/chunks/ssr/app_(app)_loading_tsx_0foisva._.js")
R.c("server/chunks/ssr/app_(app)_impulsar_loading_tsx_0g9lc8h._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_impulsar_page_actions_0q1k3f5.js")
R.m(251215)
module.exports=R.m(251215).exports
