var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/stats/historico-cobros/route.js")
R.c("server/chunks/[root-of-the-server]__0qp.-qk._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_stats_historico-cobros_route_actions_05r9f6v.js")
R.m(640113)
module.exports=R.m(640113).exports
