var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/rutas/optimizar/route.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__0ofgmt.._.js")
R.c("server/chunks/[root-of-the-server]__0hqmy_2._.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_rutas_optimizar_route_actions_02u2v9s.js")
R.m(342903)
module.exports=R.m(342903).exports
