var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/notif-reglas/test/route.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__13l_2m8._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0ofgmt.._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/node_modules_0e0ktrw._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_notif-reglas_test_route_actions_07.uq3k.js")
R.m(790206)
module.exports=R.m(790206).exports
