var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/rutas-fijas/generar/route.js")
R.c("server/chunks/[root-of-the-server]__07evgdv._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_rutas-fijas_generar_route_actions_02uzzl..js")
R.m(398190)
module.exports=R.m(398190).exports
