var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/mi-empresa/modo/route.js")
R.c("server/chunks/[root-of-the-server]__01m6q1e._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_mi-empresa_modo_route_actions_0q1ur9a.js")
R.m(684795)
module.exports=R.m(684795).exports
