// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(app)/bodega/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bodega/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(app)/bodega/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/bodega/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bodega">> = Specific
  const handler = {} as typeof import("../../app/(app)/bodega/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/cartera/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cartera">> = Specific
  const handler = {} as typeof import("../../app/(app)/cartera/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clientes">> = Specific
  const handler = {} as typeof import("../../app/(app)/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/cobros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cobros">> = Specific
  const handler = {} as typeof import("../../app/(app)/cobros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/code">> = Specific
  const handler = {} as typeof import("../../app/(app)/code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/configuracion/almacenamiento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracion/almacenamiento">> = Specific
  const handler = {} as typeof import("../../app/(app)/configuracion/almacenamiento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracion">> = Specific
  const handler = {} as typeof import("../../app/(app)/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/egresos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/egresos">> = Specific
  const handler = {} as typeof import("../../app/(app)/egresos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/empleados/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empleados">> = Specific
  const handler = {} as typeof import("../../app/(app)/empleados/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/empresas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empresas">> = Specific
  const handler = {} as typeof import("../../app/(app)/empresas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/gastos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gastos">> = Specific
  const handler = {} as typeof import("../../app/(app)/gastos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/historial-turnos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/historial-turnos">> = Specific
  const handler = {} as typeof import("../../app/(app)/historial-turnos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/historial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/historial">> = Specific
  const handler = {} as typeof import("../../app/(app)/historial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/impulsadora/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/impulsadora">> = Specific
  const handler = {} as typeof import("../../app/(app)/impulsadora/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/impulsar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/impulsar">> = Specific
  const handler = {} as typeof import("../../app/(app)/impulsar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/impulsos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/impulsos">> = Specific
  const handler = {} as typeof import("../../app/(app)/impulsos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/ingresos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ingresos">> = Specific
  const handler = {} as typeof import("../../app/(app)/ingresos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/inicio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inicio">> = Specific
  const handler = {} as typeof import("../../app/(app)/inicio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/inventario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventario">> = Specific
  const handler = {} as typeof import("../../app/(app)/inventario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/listas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listas">> = Specific
  const handler = {} as typeof import("../../app/(app)/listas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/mapa-ruta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mapa-ruta">> = Specific
  const handler = {} as typeof import("../../app/(app)/mapa-ruta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/mapa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mapa">> = Specific
  const handler = {} as typeof import("../../app/(app)/mapa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/mi-ruta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mi-ruta">> = Specific
  const handler = {} as typeof import("../../app/(app)/mi-ruta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor">> = Specific
  const handler = {} as typeof import("../../app/(app)/monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/ordenes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ordenes">> = Specific
  const handler = {} as typeof import("../../app/(app)/ordenes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/precios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/precios">> = Specific
  const handler = {} as typeof import("../../app/(app)/precios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/recaudos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recaudos">> = Specific
  const handler = {} as typeof import("../../app/(app)/recaudos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/reportes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reportes">> = Specific
  const handler = {} as typeof import("../../app/(app)/reportes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/rutas-entregas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rutas-entregas">> = Specific
  const handler = {} as typeof import("../../app/(app)/rutas-entregas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/rutas-fijas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rutas-fijas">> = Specific
  const handler = {} as typeof import("../../app/(app)/rutas-fijas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/rutas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rutas">> = Specific
  const handler = {} as typeof import("../../app/(app)/rutas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock">> = Specific
  const handler = {} as typeof import("../../app/(app)/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/trazabilidad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trazabilidad">> = Specific
  const handler = {} as typeof import("../../app/(app)/trazabilidad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/turno/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/turno">> = Specific
  const handler = {} as typeof import("../../app/(app)/turno/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/ventas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ventas">> = Specific
  const handler = {} as typeof import("../../app/(app)/ventas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/visitas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visitas">> = Specific
  const handler = {} as typeof import("../../app/(app)/visitas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cartera/recibo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cartera/recibo">> = Specific
  const handler = {} as typeof import("../../app/cartera/recibo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pago-exitoso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pago-exitoso">> = Specific
  const handler = {} as typeof import("../../app/pago-exitoso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pdf-cotizacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pdf-cotizacion">> = Specific
  const handler = {} as typeof import("../../app/pdf-cotizacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pdf-impulso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pdf-impulso">> = Specific
  const handler = {} as typeof import("../../app/pdf-impulso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recaudo/recibo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recaudo/recibo">> = Specific
  const handler = {} as typeof import("../../app/recaudo/recibo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registro">> = Specific
  const handler = {} as typeof import("../../app/registro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/alertas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alertas">> = Specific
  const handler = {} as typeof import("../../app/api/alertas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/almacenamiento/comprar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/almacenamiento/comprar">> = Specific
  const handler = {} as typeof import("../../app/api/almacenamiento/comprar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/almacenamiento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/almacenamiento">> = Specific
  const handler = {} as typeof import("../../app/api/almacenamiento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/asistente/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/asistente/historial">> = Specific
  const handler = {} as typeof import("../../app/api/asistente/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/asistente/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/asistente">> = Specific
  const handler = {} as typeof import("../../app/api/asistente/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/salud/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/salud">> = Specific
  const handler = {} as typeof import("../../app/api/audit/salud/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/invalidate-cache/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/invalidate-cache">> = Specific
  const handler = {} as typeof import("../../app/api/auth/invalidate-cache/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/backfill-fechafactura/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/backfill-fechafactura">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/backfill-fechafactura/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/buscar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/buscar">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/buscar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/contadores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/contadores">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/contadores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/despacho-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/despacho-log">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/despacho-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/despacho-log/verificar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/despacho-log/verificar">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/despacho-log/verificar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/despachos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/despachos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/despachos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/despachos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/despachos">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/despachos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/empresas-origen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/empresas-origen">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/empresas-origen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/empresas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/empresas">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/empresas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/foto/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/foto/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/foto/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/foto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/foto">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/foto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/rellenar-ciudades/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/rellenar-ciudades">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/rellenar-ciudades/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/sync-auto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/sync-auto">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/sync-auto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bodega/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bodega/sync">> = Specific
  const handler = {} as typeof import("../../app/api/bodega/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cache/warmup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cache/warmup">> = Specific
  const handler = {} as typeof import("../../app/api/cache/warmup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/[clienteId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/[clienteId]">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/[clienteId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/edades-snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/edades-snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/edades-snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/edades/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/edades">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/edades/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/metas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/metas">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/metas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/pago-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/pago-sync">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/pago-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/pdf">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/recibo-publico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/recibo-publico">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/recibo-publico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/recibo-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/recibo-token">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/recibo-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/recibo/[pagoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/recibo/[pagoId]">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/recibo/[pagoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/resumen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/resumen">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/resumen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/sync">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cartera/voucher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cartera/voucher">> = Specific
  const handler = {} as typeof import("../../app/api/cartera/voucher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/[id]/gps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/[id]/gps">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/[id]/gps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/[id]/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/[id]/meta">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/[id]/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/[id]/promedio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/[id]/promedio">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/[id]/promedio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/gps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/gps">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/gps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/meta">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/resync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/resync">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/resync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/comisiones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comisiones">> = Specific
  const handler = {} as typeof import("../../app/api/comisiones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/configuracion/bodega-inicio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracion/bodega-inicio">> = Specific
  const handler = {} as typeof import("../../app/api/configuracion/bodega-inicio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/configuracion/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracion/password">> = Specific
  const handler = {} as typeof import("../../app/api/configuracion/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/last-run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/last-run">> = Specific
  const handler = {} as typeof import("../../app/api/cron/last-run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deploy/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deploy/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/deploy/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/egresos/abono/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/egresos/abono">> = Specific
  const handler = {} as typeof import("../../app/api/egresos/abono/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/egresos/categorias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/egresos/categorias">> = Specific
  const handler = {} as typeof import("../../app/api/egresos/categorias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/egresos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/egresos">> = Specific
  const handler = {} as typeof import("../../app/api/egresos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/egresos/url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/egresos/url">> = Specific
  const handler = {} as typeof import("../../app/api/egresos/url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/egresos/voucher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/egresos/voucher">> = Specific
  const handler = {} as typeof import("../../app/api/egresos/voucher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/primer-recibo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/primer-recibo">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/primer-recibo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/slot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/slot">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/slot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empresa/despachos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresa/despachos">> = Specific
  const handler = {} as typeof import("../../app/api/empresa/despachos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empresas-vinculadas/conectar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas-vinculadas/conectar">> = Specific
  const handler = {} as typeof import("../../app/api/empresas-vinculadas/conectar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empresas-vinculadas/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas-vinculadas/lookup">> = Specific
  const handler = {} as typeof import("../../app/api/empresas-vinculadas/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empresas-vinculadas/pedidos-pendientes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas-vinculadas/pedidos-pendientes">> = Specific
  const handler = {} as typeof import("../../app/api/empresas-vinculadas/pedidos-pendientes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empresas-vinculadas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas-vinculadas">> = Specific
  const handler = {} as typeof import("../../app/api/empresas-vinculadas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empresas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/empresas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empresas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas">> = Specific
  const handler = {} as typeof import("../../app/api/empresas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/entregas-externas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entregas-externas">> = Specific
  const handler = {} as typeof import("../../app/api/entregas-externas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/firma/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/firma">> = Specific
  const handler = {} as typeof import("../../app/api/firma/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gastos/evidencia/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gastos/evidencia">> = Specific
  const handler = {} as typeof import("../../app/api/gastos/evidencia/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gastos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gastos">> = Specific
  const handler = {} as typeof import("../../app/api/gastos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gastos/tipos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gastos/tipos">> = Specific
  const handler = {} as typeof import("../../app/api/gastos/tipos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gastos/voucher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gastos/voucher">> = Specific
  const handler = {} as typeof import("../../app/api/gastos/voucher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsadora/generar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsadora/generar">> = Specific
  const handler = {} as typeof import("../../app/api/impulsadora/generar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsadora/hoy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsadora/hoy">> = Specific
  const handler = {} as typeof import("../../app/api/impulsadora/hoy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsadora/meta-cliente/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsadora/meta-cliente">> = Specific
  const handler = {} as typeof import("../../app/api/impulsadora/meta-cliente/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsadora/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsadora">> = Specific
  const handler = {} as typeof import("../../app/api/impulsadora/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsar/clientes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsar/clientes">> = Specific
  const handler = {} as typeof import("../../app/api/impulsar/clientes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsar/evento/foto-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsar/evento/foto-url">> = Specific
  const handler = {} as typeof import("../../app/api/impulsar/evento/foto-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsar/evento/fotos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsar/evento/fotos">> = Specific
  const handler = {} as typeof import("../../app/api/impulsar/evento/fotos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsar/evento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsar/evento">> = Specific
  const handler = {} as typeof import("../../app/api/impulsar/evento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsar/gestion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsar/gestion">> = Specific
  const handler = {} as typeof import("../../app/api/impulsar/gestion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsar/inventario/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsar/inventario">> = Specific
  const handler = {} as typeof import("../../app/api/impulsar/inventario/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsar/rotacion-snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsar/rotacion-snapshots">> = Specific
  const handler = {} as typeof import("../../app/api/impulsar/rotacion-snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsar/rotacion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsar/rotacion">> = Specific
  const handler = {} as typeof import("../../app/api/impulsar/rotacion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsar/sugeridos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsar/sugeridos">> = Specific
  const handler = {} as typeof import("../../app/api/impulsar/sugeridos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulso/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulso/pdf">> = Specific
  const handler = {} as typeof import("../../app/api/impulso/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulso/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulso">> = Specific
  const handler = {} as typeof import("../../app/api/impulso/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulso/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulso/snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/impulso/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/impulsos/ventas-mes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impulsos/ventas-mes">> = Specific
  const handler = {} as typeof import("../../app/api/impulsos/ventas-mes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inci/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inci">> = Specific
  const handler = {} as typeof import("../../app/api/inci/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integracion/analizar-docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracion/analizar-docs">> = Specific
  const handler = {} as typeof import("../../app/api/integracion/analizar-docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integracion/conectar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracion/conectar">> = Specific
  const handler = {} as typeof import("../../app/api/integracion/conectar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integracion/estado/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracion/estado">> = Specific
  const handler = {} as typeof import("../../app/api/integracion/estado/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integracion/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracion/sync">> = Specific
  const handler = {} as typeof import("../../app/api/integracion/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integracion/transprensa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracion/transprensa">> = Specific
  const handler = {} as typeof import("../../app/api/integracion/transprensa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integracion/transprensa/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracion/transprensa/test">> = Specific
  const handler = {} as typeof import("../../app/api/integracion/transprensa/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integracion/validar-api/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracion/validar-api">> = Specific
  const handler = {} as typeof import("../../app/api/integracion/validar-api/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integracion/validar-uptres/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integracion/validar-uptres">> = Specific
  const handler = {} as typeof import("../../app/api/integracion/validar-uptres/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventario/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventario">> = Specific
  const handler = {} as typeof import("../../app/api/inventario/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventario/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventario/sync">> = Specific
  const handler = {} as typeof import("../../app/api/inventario/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/listas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/listas">> = Specific
  const handler = {} as typeof import("../../app/api/listas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mapa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mapa">> = Specific
  const handler = {} as typeof import("../../app/api/mapa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/metas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metas">> = Specific
  const handler = {} as typeof import("../../app/api/metas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mi-empresa/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mi-empresa/config">> = Specific
  const handler = {} as typeof import("../../app/api/mi-empresa/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mi-empresa/estado/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mi-empresa/estado">> = Specific
  const handler = {} as typeof import("../../app/api/mi-empresa/estado/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mi-empresa/modo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mi-empresa/modo">> = Specific
  const handler = {} as typeof import("../../app/api/mi-empresa/modo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitor">> = Specific
  const handler = {} as typeof import("../../app/api/monitor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notif-reglas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notif-reglas">> = Specific
  const handler = {} as typeof import("../../app/api/notif-reglas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notif-reglas/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notif-reglas/test">> = Specific
  const handler = {} as typeof import("../../app/api/notif-reglas/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/osrm-route/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/osrm-route">> = Specific
  const handler = {} as typeof import("../../app/api/osrm-route/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pago-info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pago-info">> = Specific
  const handler = {} as typeof import("../../app/api/pago-info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pagos/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pagos/link">> = Specific
  const handler = {} as typeof import("../../app/api/pagos/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ping">> = Specific
  const handler = {} as typeof import("../../app/api/ping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan-empresa/cron/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan-empresa/cron">> = Specific
  const handler = {} as typeof import("../../app/api/plan-empresa/cron/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan-empresa/generar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan-empresa/generar">> = Specific
  const handler = {} as typeof import("../../app/api/plan-empresa/generar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan-empresa/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan-empresa/historial">> = Specific
  const handler = {} as typeof import("../../app/api/plan-empresa/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan-empresa/pago/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan-empresa/pago">> = Specific
  const handler = {} as typeof import("../../app/api/plan-empresa/pago/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan-empresa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan-empresa">> = Specific
  const handler = {} as typeof import("../../app/api/plan-empresa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan-empresa/voucher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan-empresa/voucher">> = Specific
  const handler = {} as typeof import("../../app/api/plan-empresa/voucher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/postventa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/postventa">> = Specific
  const handler = {} as typeof import("../../app/api/postventa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/precios/publico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/precios/publico">> = Specific
  const handler = {} as typeof import("../../app/api/precios/publico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/precios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/precios">> = Specific
  const handler = {} as typeof import("../../app/api/precios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proveedores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proveedores">> = Specific
  const handler = {} as typeof import("../../app/api/proveedores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/push/desuscribir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/desuscribir">> = Specific
  const handler = {} as typeof import("../../app/api/push/desuscribir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/push/suscribir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/suscribir">> = Specific
  const handler = {} as typeof import("../../app/api/push/suscribir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recaudos/[pagoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recaudos/[pagoId]">> = Specific
  const handler = {} as typeof import("../../app/api/recaudos/[pagoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recaudos/ajuste/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recaudos/ajuste">> = Specific
  const handler = {} as typeof import("../../app/api/recaudos/ajuste/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recaudos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recaudos">> = Specific
  const handler = {} as typeof import("../../app/api/recaudos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recaudos/validar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recaudos/validar">> = Specific
  const handler = {} as typeof import("../../app/api/recaudos/validar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recibos/config/empresa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recibos/config/empresa">> = Specific
  const handler = {} as typeof import("../../app/api/recibos/config/empresa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recibos/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recibos/config">> = Specific
  const handler = {} as typeof import("../../app/api/recibos/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/registro/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registro">> = Specific
  const handler = {} as typeof import("../../app/api/registro/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/recaudos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/recaudos">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/recaudos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas-fijas/generar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas-fijas/generar">> = Specific
  const handler = {} as typeof import("../../app/api/rutas-fijas/generar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas-fijas/hoy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas-fijas/hoy">> = Specific
  const handler = {} as typeof import("../../app/api/rutas-fijas/hoy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas-fijas/meta-cliente/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas-fijas/meta-cliente">> = Specific
  const handler = {} as typeof import("../../app/api/rutas-fijas/meta-cliente/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas-fijas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas-fijas">> = Specific
  const handler = {} as typeof import("../../app/api/rutas-fijas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/[id]/adelantar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/[id]/adelantar">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/[id]/adelantar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/[id]/agregar-clientes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/[id]/agregar-clientes">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/[id]/agregar-clientes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/[id]/agregar-vinculados/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/[id]/agregar-vinculados">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/[id]/agregar-vinculados/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/cliente/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/cliente">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/cliente/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/historial">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/mi-ruta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/mi-ruta">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/mi-ruta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/optimizar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/optimizar">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/optimizar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/procesar-dia/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/procesar-dia">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/procesar-dia/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/saldos/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saldos/config">> = Specific
  const handler = {} as typeof import("../../app/api/saldos/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/saldos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saldos">> = Specific
  const handler = {} as typeof import("../../app/api/saldos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/smoke/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/smoke/auth">> = Specific
  const handler = {} as typeof import("../../app/api/smoke/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/smoke/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/smoke/test">> = Specific
  const handler = {} as typeof import("../../app/api/smoke/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sms/polling/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sms/polling">> = Specific
  const handler = {} as typeof import("../../app/api/sms/polling/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sms/procesar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sms/procesar">> = Specific
  const handler = {} as typeof import("../../app/api/sms/procesar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stats/historico-cobros/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/historico-cobros">> = Specific
  const handler = {} as typeof import("../../app/api/stats/historico-cobros/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stats/historico-mes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/historico-mes">> = Specific
  const handler = {} as typeof import("../../app/api/stats/historico-mes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stats/historico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/historico">> = Specific
  const handler = {} as typeof import("../../app/api/stats/historico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats">> = Specific
  const handler = {} as typeof import("../../app/api/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stats/snapshot-mes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/snapshot-mes">> = Specific
  const handler = {} as typeof import("../../app/api/stats/snapshot-mes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stock">> = Specific
  const handler = {} as typeof import("../../app/api/stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stock/sugerido/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stock/sugerido/historial">> = Specific
  const handler = {} as typeof import("../../app/api/stock/sugerido/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stock/sugerido/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stock/sugerido">> = Specific
  const handler = {} as typeof import("../../app/api/stock/sugerido/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stock/sugerido/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stock/sugerido/snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/stock/sugerido/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stock/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stock/sync">> = Specific
  const handler = {} as typeof import("../../app/api/stock/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/superadmin/code-map/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/superadmin/code-map">> = Specific
  const handler = {} as typeof import("../../app/api/superadmin/code-map/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/superadmin/empleados-lista/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/superadmin/empleados-lista">> = Specific
  const handler = {} as typeof import("../../app/api/superadmin/empleados-lista/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/superadmin/empresas-lista/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/superadmin/empresas-lista">> = Specific
  const handler = {} as typeof import("../../app/api/superadmin/empresas-lista/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync-empleados/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync-empleados">> = Specific
  const handler = {} as typeof import("../../app/api/sync-empleados/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync/clientes-total/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/clientes-total">> = Specific
  const handler = {} as typeof import("../../app/api/sync/clientes-total/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync/delta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/delta">> = Specific
  const handler = {} as typeof import("../../app/api/sync/delta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync/nocturno/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/nocturno">> = Specific
  const handler = {} as typeof import("../../app/api/sync/nocturno/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync/transprensa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/transprensa">> = Specific
  const handler = {} as typeof import("../../app/api/sync/transprensa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync/ventas-historico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/ventas-historico">> = Specific
  const handler = {} as typeof import("../../app/api/sync/ventas-historico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync/ventas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/ventas">> = Specific
  const handler = {} as typeof import("../../app/api/sync/ventas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/taxbot/numero/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/taxbot/numero">> = Specific
  const handler = {} as typeof import("../../app/api/taxbot/numero/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/taxbot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/taxbot">> = Specific
  const handler = {} as typeof import("../../app/api/taxbot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trazabilidad/buscar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trazabilidad/buscar">> = Specific
  const handler = {} as typeof import("../../app/api/trazabilidad/buscar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trazabilidad/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trazabilidad">> = Specific
  const handler = {} as typeof import("../../app/api/trazabilidad/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/turnos/admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/turnos/admin">> = Specific
  const handler = {} as typeof import("../../app/api/turnos/admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/turnos/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/turnos/historial">> = Specific
  const handler = {} as typeof import("../../app/api/turnos/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/turnos/procesar-dia/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/turnos/procesar-dia">> = Specific
  const handler = {} as typeof import("../../app/api/turnos/procesar-dia/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/turnos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/turnos">> = Specific
  const handler = {} as typeof import("../../app/api/turnos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upgrade-empleados/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upgrade-empleados">> = Specific
  const handler = {} as typeof import("../../app/api/upgrade-empleados/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vendedor/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendedor/stats">> = Specific
  const handler = {} as typeof import("../../app/api/vendedor/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vendedor/sync-inicial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendedor/sync-inicial">> = Specific
  const handler = {} as typeof import("../../app/api/vendedor/sync-inicial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vendedor/sync-ventas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendedor/sync-ventas">> = Specific
  const handler = {} as typeof import("../../app/api/vendedor/sync-ventas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/vendedor/ventas-live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendedor/ventas-live">> = Specific
  const handler = {} as typeof import("../../app/api/vendedor/ventas-live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/version">> = Specific
  const handler = {} as typeof import("../../app/api/version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/visitas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitas/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/visitas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/visitas/admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitas/admin">> = Specific
  const handler = {} as typeof import("../../app/api/visitas/admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/visitas/impulsos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitas/impulsos">> = Specific
  const handler = {} as typeof import("../../app/api/visitas/impulsos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/visitas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitas">> = Specific
  const handler = {} as typeof import("../../app/api/visitas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/visitas/todas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitas/todas">> = Specific
  const handler = {} as typeof import("../../app/api/visitas/todas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voucher-blob/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voucher-blob">> = Specific
  const handler = {} as typeof import("../../app/api/voucher-blob/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voucher-huella/delta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voucher-huella/delta">> = Specific
  const handler = {} as typeof import("../../app/api/voucher-huella/delta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
