var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/vendedor/stats/route.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0mywnjy.js")
R.c("server/chunks/[root-of-the-server]__07goo8e._.js")
R.c("server/chunks/[root-of-the-server]__0ofgmt.._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_vendedor_stats_route_actions_0hoxn5i.js")
R.m(664252)
module.exports=R.m(664252).exports
