var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/rutas/mi-ruta/route.js")
R.c("server/chunks/[root-of-the-server]__0-4w~6i._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0ife_8y.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_rutas_mi-ruta_route_actions_0kjlkx4.js")
R.m(936432)
module.exports=R.m(936432).exports
