var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/recaudos/route.js")
R.c("server/chunks/[root-of-the-server]__0r~0m9m._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0i6011p.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_recaudos_route_actions_0o9kxnw.js")
R.m(248438)
module.exports=R.m(248438).exports
