var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/rutas/[id]/adelantar/route.js")
R.c("server/chunks/[root-of-the-server]__0d5fw_k._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_rutas_[id]_adelantar_route_actions_0ki8z~r.js")
R.m(237270)
module.exports=R.m(237270).exports
