var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/recaudos/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0chzybw._.js")
R.c("server/chunks/ssr/node_modules_05l396c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0.cn8__.js")
R.c("server/chunks/ssr/[root-of-the-server]__0khh7ip._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sc-y4u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(app)_layout_tsx_0i-3xbc._.js")
R.c("server/chunks/ssr/app_(app)_loading_tsx_0foisva._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_recaudos_page_actions_0.zrco3.js")
R.m(93959)
module.exports=R.m(93959).exports
