var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/stock/route.js")
R.c("server/chunks/[root-of-the-server]__01s_23o._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_stock_route_actions_12q1y9v.js")
R.m(541279)
module.exports=R.m(541279).exports
