var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/recaudo/recibo/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gcyg51._.js")
R.c("server/chunks/ssr/node_modules_05l396c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0kvgci4.js")
R.c("server/chunks/ssr/[root-of-the-server]__0khh7ip._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sc-y4u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_recaudo_recibo_page_actions_0.y0~rv.js")
R.m(530982)
module.exports=R.m(530982).exports
