var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/clientes/[id]/meta/route.js")
R.c("server/chunks/[root-of-the-server]__0vzw8m3._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_clientes_[id]_meta_route_actions_0sin67d.js")
R.m(794984)
module.exports=R.m(794984).exports
