var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/visitas/impulsos/route.js")
R.c("server/chunks/[root-of-the-server]__0vqpp0f._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_visitas_impulsos_route_actions_0yb-cwi.js")
R.m(590375)
module.exports=R.m(590375).exports
