var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/empresas-vinculadas/conectar/route.js")
R.c("server/chunks/[root-of-the-server]__00fq-4n._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_empresas-vinculadas_conectar_route_actions_04_0gzn.js")
R.m(828176)
module.exports=R.m(828176).exports
