var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/clientes/route.js")
R.c("server/chunks/[root-of-the-server]__05~ahc6._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0-5kqhk.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/_next-internal_server_app_api_clientes_route_actions_0c_j1f6.js")
R.m(989414)
module.exports=R.m(989414).exports
