var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/bodega/empresas-origen/route.js")
R.c("server/chunks/[root-of-the-server]__0kz2izd._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__09~8~gw._.js")
R.c("server/chunks/[root-of-the-server]__0-orlhy._.js")
R.c("server/chunks/[root-of-the-server]__0la1agp._.js")
R.c("server/chunks/_next-internal_server_app_api_bodega_empresas-origen_route_actions_0i--d0h.js")
R.m(76833)
module.exports=R.m(76833).exports
